# Generated by Django 4.1.3 on 2022-12-16 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('dose_mg', models.FloatField()),
                ('infusion_period_minutes', models.IntegerField(null=True)),
                ('stage', models.IntegerField(null=True)),
                ('drug_name', models.CharField(max_length=180, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='patient.patient')),
            ],
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['patient', 'date'], name='treatment_t_patient_e773d9_idx'),
        ),
    ]
